/{\/\* Notifications \(placeholder\) \*\/}/ {
  print "        {/* Notifications */}"
  print "        <DropdownMenu>"
  print "          <DropdownMenuTrigger asChild>"
  print "            <Button variant=\"ghost\" size=\"icon\" className=\"h-9 w-9 relative hidden sm:flex\" aria-label=\"Notifications\">"
  print "              <Bell className=\"h-5 w-5\" />"
  print "              {unreadCount > 0 && ("
  print "                <span className=\"absolute top-1.5 right-1.5 h-2 w-2 rounded-full bg-destructive\" />"
  print "              )}"
  print "            </Button>"
  print "          </DropdownMenuTrigger>"
  print "          <DropdownMenuContent align=\"end\" className=\"w-80\">"
  print "            <div className=\"flex items-center justify-between px-4 py-2 border-b\">"
  print "              <span className=\"font-semibold text-sm\">Notifications</span>"
  print "              {unreadCount > 0 && ("
  print "                <Button variant=\"ghost\" size=\"sm\" className=\"h-auto p-0 text-xs text-primary\" onClick={markAllAsRead}>"
  print "                  Mark all as read"
  print "                </Button>"
  print "              )}"
  print "            </div>"
  print "            <div className=\"max-h-[300px] overflow-y-auto\">"
  print "              {notifications.length === 0 ? ("
  print "                <div className=\"p-4 text-center text-sm text-muted-foreground\">"
  print "                  No notifications"
  print "                </div>"
  print "              ) : ("
  print "                notifications.map((notif) => ("
  print "                  <div key={notif.id} className={`p-4 border-b last:border-0 ${notif.read ? '\\''opacity-60'\\' : '\\''bg-primary/5'\\''}`}>"
  print "                    <div className=\"flex justify-between items-start mb-1\">"
  print "                      <span className=\"font-medium text-sm\">{notif.title}</span>"
  print "                      <Button variant=\"ghost\" size=\"sm\" className=\"h-5 w-5 p-0 opacity-50 hover:opacity-100\" onClick={() => dismissNotification(notif.id)}>"
  print "                        &times;"
  print "                      </Button>"
  print "                    </div>"
  print "                    <p className=\"text-xs text-muted-foreground mb-2\">{notif.message}</p>"
  print "                    <div className=\"flex justify-between items-center\">"
  print "                      <span className=\"text-[10px] text-muted-foreground\">{new Date(notif.timestamp).toLocaleTimeString()}</span>"
  print "                      {!notif.read && ("
  print "                        <Button variant=\"ghost\" size=\"sm\" className=\"h-auto p-0 text-[10px] text-primary\" onClick={() => markAsRead(notif.id)}>"
  print "                          Mark read"
  print "                        </Button>"
  print "                      )}"
  print "                    </div>"
  print "                  </div>"
  print "                ))"
  print "              )}"
  print "            </div>"
  print "            {notifications.length > 0 && ("
  print "              <div className=\"p-2 border-t text-center\">"
  print "                <Button variant=\"ghost\" size=\"sm\" className=\"w-full text-xs\" onClick={clearAll}>"
  print "                  Clear all"
  print "                </Button>"
  print "              </div>"
  print "            )}"
  print "          </DropdownMenuContent>"
  print "        </DropdownMenu>"
  
  getline
  getline
  getline
  next
}
{ print }
