import { recommendStandards } from './recommendation';
import "dotenv/config";

import * as express from 'express';
import * as cors from 'cors';
import { prisma } from './prisma';
import { semanticSearch, generateRagAnswer } from './rag';

const app = express();


app.use(cors());
app.use(express.json());

app.get('/api/standards', async (req, res) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 20;
    const search = (req.query.q as string) || (req.query.search as string);
    const group = req.query.group as string;
    const subGroup = req.query.subGroup as string;
    const status = req.query.status as string;

    const skip = (page - 1) * limit;
    
    const whereClause: any = {};
    
    if (search) {
      whereClause.OR = [
        { isNumber: { contains: search } },
        { title: { contains: search } },
        { technicalDepartment: { contains: search } },
        { sectionalCommittee: { contains: search } }
      ];
    }
    
    if (status && status !== 'all' && status !== 'All') {
      whereClause.status = { contains: status };
    }
    
    if (group) {
      whereClause.groups = {
        some: {
          group: { name: group }
        }
      };
    }
    
    if (subGroup) {
      whereClause.subGroups = {
        some: {
          subGroup: { name: subGroup }
        }
      };
    }
    
    const [standards, total] = await Promise.all([
      prisma.standard.findMany({
        where: whereClause,
        skip,
        take: limit,
        orderBy: { isNumber: 'asc' },
        include: { groups: { include: { group: true } }, subGroups: { include: { subGroup: true } } }
      }),
      prisma.standard.count({ where: whereClause })
    ]);
    
    res.json({
      data: standards,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/standards/search', async (req, res) => {
  const query = req.query.q as string;
  try {
    let chunks = [];
    if (query) {
      chunks = await prisma.documentChunk.findMany({
        where: {
          text: { contains: query }
        },
        include: {
          document: true,
          page: true
        },
        take: 20
      });
    }
    // Forward the rest to /api/standards logic for standard metadata
    res.redirect(`/api/standards?${new URLSearchParams(req.query as any).toString()}`);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/standards/:id', async (req, res) => {
  try {
    const standard = await prisma.standard.findUnique({
      where: { id: req.params.id },
      include: { document: true }
    });
    if (!standard) return res.status(404).json({ error: 'Not found' });
    res.json(standard);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/documents/:id', async (req, res) => {
  try {
    const document = await prisma.document.findUnique({
      where: { id: req.params.id },
      include: { standards: true }
    });
    if (!document) return res.status(404).json({ error: 'Not found' });
    res.json(document);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/documents/:id/pages', async (req, res) => {
  try {
    const pages = await prisma.documentPage.findMany({
      where: { documentId: req.params.id },
      orderBy: { pageNumber: 'asc' }
    });
    res.json(pages);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Phase 4: RAG Chat API
app.post('/api/chat', async (req, res) => {
  const { message, language, history } = req.body;
  if (!message) return res.status(400).json({ success: false, data: null, error: { code: 'BAD_REQUEST', message: 'Message is required' } });

  try {
    const contextQuery = (history && history.length > 0) ? (history[history.length - 2]?.content || '') + ' ' + message : message;
    
    console.log(`[Chat API] Query: "${message}"`);
    console.log(`[Chat API] Context Query for RAG: "${contextQuery}"`);
    
    const topChunks = await semanticSearch(contextQuery, 3);
    console.log(`[Chat API] RAG Results: ${topChunks.length} chunks retrieved.`);
    if (topChunks.length > 0) {
      console.log(`[Chat API] Top Similarity Score: ${topChunks[0].score}`);
    }
    
    let answer = '';
    let provider = 'unknown';
    try {
      const ragResult = await generateRagAnswer(message, topChunks, language || 'en', history || []);
      answer = ragResult.answer;
      provider = ragResult.provider;
      console.log(`[Chat API] LLM Answer generated by ${provider} (Length: ${answer.length})`);
    } catch (llmErr: any) {
      console.error("[Chat API] AI Generation Error:", llmErr.message);
      let errorMsg = 'Failed to generate response.';
      let errCode = 'AI_GENERATION_FAILED';
      
      if (llmErr.message === 'AI_TIMEOUT') {
        errorMsg = 'The AI service took too long to respond. Please try again.';
        errCode = 'AI_TIMEOUT';
      } else if (llmErr.message === 'AI_RATE_LIMIT') {
        errorMsg = 'The AI service is temporarily busy due to high traffic. Please wait a moment.';
        errCode = 'AI_RATE_LIMIT';
      } else if (llmErr.message === 'AI_SERVICE_UNAVAILABLE') {
        errorMsg = 'The AI service is currently unavailable. We are recovering, please try again shortly.';
        errCode = 'AI_SERVICE_UNAVAILABLE';
      } else if (llmErr.message === 'AI_NOT_CONFIGURED') {
        errorMsg = 'The AI Assistant is not configured on the server.';
        errCode = 'AI_NOT_CONFIGURED';
      }
      
      return res.status(200).json({
        success: false,
        data: null,
        error: { code: errCode, message: errorMsg }
      });
    }

    const citations = topChunks.map((c: any, index: number) => ({
      id: c.id,
      citationIndex: index + 1,
      documentTitle: c.document?.title,
      standardNumber: c.standardNumber,
      pageNumber: c.page?.pageNumber,
      section: c.section?.heading,
      text: c.text,
      score: c.score
    }));

    return res.status(200).json({
      success: true,
      data: {
        answer,
        provider,
        citations,
        retrievedChunksCount: topChunks.length
      },
      error: null
    });
  } catch (err: any) {
    console.error('[Chat API] Unhandled exception:', err);
    return res.status(500).json({ 
      success: false, 
      data: null, 
      error: { code: 'INTERNAL_ERROR', message: 'An unexpected internal error occurred.' }
    });
  }
});

import { aiService } from './ai-provider';
app.get('/api/health', async (req, res) => {
  try {
    const standards = await prisma.standard.count();
    const certifications = await prisma.product.count();
    const laboratories = await prisma.laboratory.count();
    res.json({
      database: 'connected',
      standards,
      certifications,
      laboratories,
      timestamp: new Date().toISOString()
    });
  } catch(e) {
    res.status(500).json({ database: 'disconnected', error: 'Database unavailable' });
  }
});
app.get('/api/health/ai', (req, res) => {
  res.json({ status: aiService.getStatus(), timestamp: new Date().toISOString() });
});


// --- CERTIFICATIONS API ---
app.get('/api/certifications', async (req, res) => {
  try {
    const q = (req.query.q as string) || '';
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 20;
    const skip = (page - 1) * limit;

    const whereClause: any = {};
    if (q.trim()) {
      whereClause.OR = [
        { name: { contains: q } },
        { standard: { isNumber: { contains: q } } },
        { standard: { title: { contains: q } } },
        { category: { contains: q } }
      ];
    }
    
    const [products, total] = await Promise.all([
      prisma.product.findMany({
        where: whereClause,
        include: {
          scheme: {
            include: { requirements: { orderBy: { order: 'asc' } } }
          },
          standard: true
        },
        skip,
        take: limit
      }),
      prisma.product.count({ where: whereClause })
    ]);
    
    res.json({ 
      products, 
      total, 
      page, 
      limit, 
      totalPages: Math.ceil(total / limit),
      hasNext: skip + limit < total,
      hasPrevious: page > 1
    });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: 'Failed to fetch certifications' });
  }
});

// --- LABORATORIES API ---
app.get('/api/laboratories', async (req, res) => {
  const query = req.query.q as string;
  const state = req.query.state as string;
  const category = req.query.category as string;
  
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 20;
  const skip = (page - 1) * limit;
  
  try {
    const whereClause: any = {};
    if (query) {
      whereClause.OR = [
        { name: { contains: query } },
        { labCode: { contains: query } },
        { address: { contains: query } }
      ];
    }
    if (state && state !== 'All States') {
      whereClause.state = { contains: state };
    }
    if (category && category !== 'All Categories') {
      whereClause.category = { equals: category };
    }

    const total = await prisma.laboratory.count({ where: whereClause });
    const laboratories = await prisma.laboratory.findMany({
      where: whereClause,
      skip,
      take: limit,
      orderBy: { labCode: 'asc' }
    });
    
    res.json({
      data: laboratories,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/laboratories/:id', async (req, res) => {
  try {
    const lab = await prisma.laboratory.findUnique({
      where: { id: req.params.id }
    });
    if (!lab) return res.status(404).json({ error: 'Laboratory not found' });
    res.json(lab);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

const PORT = 3001;
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});


// --- RECOMMENDATIONS API (Phase 5.1) ---
app.post('/api/recommendations', async (req, res) => {
  try {
    const { query } = req.body;
    if (!query) {
      return res.status(400).json({ error: 'Query is required' });
    }
    const result = await recommendStandards(query);
    res.json(result);
  } catch (error: any) {
    console.error('Recommendation API error:', error);
    res.status(500).json({ error: 'Failed to generate recommendations' });
  }
});

import { unifiedSearch } from './search';

// --- UNIFIED SEARCH API (Phase 5.3) ---
app.get('/api/search', async (req, res) => {
  try {
    const q = req.query.q as string;
    const limit = parseInt(req.query.limit as string) || 20;
    const offset = parseInt(req.query.offset as string) || 0;
    
    if (!q) {
      return res.json({ standards: [], products: [], laboratories: [], totalResults: 0 });
    }
    
    const results = await unifiedSearch(q, limit, offset);
    res.json(results);
  } catch (error: any) {
    console.error('Search API error:', error);
    res.status(500).json({ error: 'Search failed' });
  }
});

import { getDashboard, logActivity, toggleSavedStandard } from './dashboard';

// --- DASHBOARD API (Phase 5.5) ---
app.get('/api/dashboard', async (req, res) => {
  try {
    const sessionId = req.headers['x-session-id'] as string || 'default-session';
    const data = await getDashboard(sessionId);
    res.json(data);
  } catch (error: any) {
    console.error('Dashboard error:', error);
    res.status(500).json({ error: 'Failed to fetch dashboard' });
  }
});

app.post('/api/activity', async (req, res) => {
  try {
    const sessionId = req.headers['x-session-id'] as string || 'default-session';
    const { activityType, entityId, details } = req.body;
    await logActivity(sessionId, activityType, entityId, details);
    res.json({ success: true });
  } catch (error: any) {
    res.status(500).json({ error: 'Failed to log activity' });
  }
});

app.post('/api/saved-standards', async (req, res) => {
  try {
    const sessionId = req.headers['x-session-id'] as string || 'default-session';
    const { standardId } = req.body;
    const result = await toggleSavedStandard(sessionId, standardId);
    res.json(result);
  } catch (error: any) {
    res.status(500).json({ error: 'Failed to toggle save' });
  }
});

import { getNotifications } from './dashboard';

app.get('/api/notifications/poll', async (req, res) => {
  try {
    const sessionId = req.headers['x-session-id'] as string || 'default-session';
    const notifs = await getNotifications(sessionId);
    res.json(notifs);
  } catch (error: any) {
    res.status(500).json({ error: 'Failed to poll notifications' });
  }
});
